sick_scan2: # configuration for sick_scan2_tim_5xx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "169.254.224.167"
    frame_id : "back_base_scan"
    scanner_name : "sick_tim_5xx"
    port : 2112
    min_ang : -0.610865 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : 3.66519 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    #max_range : 10.0 #in meters, for 551 and 561
    max_range : 25.0 #in meters, for 571
